### ISSUE TITLE
Crushes issues.

### ISSUE THREAD

**Issue by skywalkercaptures** [coltonon/OpenGameCamera#16]
Hey guys! First of all, thanks for give us this tool, it's really good and is fun to make some captures. Second, I'm brand new to this so, forgive me if I made some silly stuff.
Third, I have crushes issues. I don't know if the last Battlefront 2 update made it, or if it happens when I updated JAVA, or if it was for any Windows update.
So, I lunch the game, inject the DLL, and it does, but then it freeze and close the game. 
That's all I got for now, I will let you know if I make it work but, do you have any idea of what it could it be?? Thanks again and great job!

**Comment by Dangercato** [comment]
The last game update changed the cam offsets we were using. The latest OGC build has fixed this and is available on our GitHub page.

A pre-built version will be made available later.
