### ISSUE TITLE
Camera Audio When Player Is Far Distance.

### ISSUE THREAD

**Issue by CroftGaming** [coltonon/OpenGameCamera#18]
f5 mode with the camera moves everywhere possible to hear the audio from far distance. Great job on  this !!! It's amazing!

**Comment by Dangercato** [comment]
Could you please elaborate more on what you mean.

**Comment by CroftGaming** [comment]
ok so when you move around in camera mode and good far distance (from the player) u cannot hear the audio for example u hear a faint blaster fire in the background from where the player is located but don't hear the troopers when u move the camera around the map. cheers

**Comment by Dangercato** [comment]
This isn't something we're planning to fix.

Your best bet is to do some foley work by extracting sounds from the game using the Frosty Tool Suite.
