### ISSUE TITLE
Full Res SSR checkbox

### ISSUE THREAD

**Issue by Dyvinia** [coltonon/OpenGameCamera#2]
SSR is currently half res, would be nice to have it at full res

**Comment by coltonon** [comment]
Should be in [this](https://typeinfo.studio/?file=/dumps/starwarsbattlefrontii-11-02-2019.json&typeInfo=GlobalPostProcessSettings&node=true) class, `ScreenSpaceRaytraceQuality` or `ScreenSpaceRaytraceFullresEnable`
