### ISSUE TITLE
Couple changes that would help filmmakers. FOV and camera speed.

### ISSUE THREAD

**Issue by spikulGuy** [coltonon/OpenGameCamera#31]
A slider with FOV values.
This would be very helpful with videos, machinimas and such.

More control over the speed of camera movement.
Beeing able to choose at what speed camera moves would be a great addition. RIght now there is slow/normal/fast with ctrl and shift keys. I think maybe a slider or values changer would be good. Beeing able to change the speed on the go while filming would be a dream come true.

**Comment by Dyvinia** [comment]
Working on adding this rn
