### ISSUE TITLE
Error Building LaunchOpenGameCamera - Unresolved External Symbol 

### ISSUE THREAD

**Issue by leganrac-alt** [coltonon/OpenGameCamera#48]
**Error Code**: 	LNK2019	
**Description**: 	unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	
**Project**: 	C:\Users\ [myusername]\Source\Repos\OpenGameCamera\OpenGameCamera.sln	
**File**: 	C:\Users\ [myusername]\Source\Repos\OpenGameCamera\MSVCRTD.lib(exe_main.obj)	
**Line**: 1	

I am building the code with Admin rights enabled -- if that even matters -- and when I launch the launcher it crashes the game instantly. I don't know if these issues are related, but it's an issue nonetheless.
If this is somehow an issue with my version of the code/Visual Studio/etc. please let me know so I don't waste any more of our time (I'm completely new to GitHub/coding/etc. of this, so if there are any rules/norms I have broken I apologize).

**Comment by leganrac-alt** [comment]
Just noticed that I don't need to build LaunchOpenGameCamera, only OpenGameCamera. And there is a convenient guide in the Discord...

**Comment by leganrac-alt** [comment]
Guide didn't solve problem... Will just leave open until issue is addressed.

**Comment by battledash** [comment]
Go to your project properties -> linker -> additional library dependencies, and add `{your VS path}\VC\lib`. Eg; `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib`.

**Comment by leganrac-alt** [comment]
I have no `lib` folder in that example path, but I found one of the same name in the path listed below. Should that have fixed the issue or am I missing a folder?
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\VS\lib`
The folder in the path above contains `arm`, `onecore`, `x64`, and `x86` folders if those are what matter.
