### ISSUE TITLE
(Bug) Freeze Time

### ISSUE THREAD

**Issue by Dyvinia** [coltonon/OpenGameCamera#6]
Holding the freeze time button will cause it to alternate between freeze time and normal time. This becomes an issue if you don't release the key fast enough which results in the time resuming

**Comment by coltonon** [comment]
This was actually intended to be a feature, since once you press the key you cannot re-press it for another 250ms by default. Idea being you can toggle it quickly to get the perfect frame, but I understand how it can be annoying. Will fix.

**Comment by Dyvinia** [comment]
Perhaps an option to enable/disable that could be helpful

**Comment by coltonon** [comment]
[here](https://github.com/coltonon/OpenGameCamera/blob/7a9851a24350e5afb1d34ef37c667070e293371d/OpenGameCamera/Source.cpp#L144) is the line that controls it, I'll probably remove the `100` so it defaults back to 250, then those who wanna change it can just modify that value.

**Comment by coltonon** [comment]
Reset back to 250
